server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy da API
    location /api/ {
        proxy_pass         http://api:3000/;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    # Frontend — serve arquivos estáticos
    location / {
        try_files $uri $uri/ =404;
    }

    # Desabilita acesso direto à pasta backend e db
    location ~ ^/(backend|db|docs)/ {
        deny all;
        return 404;
    }
}
